rm clientupdates.ibc
rm 00elementalmagicks-idx.ibc
rm main.ibc
rm objects_advanced.ibc
rm objects_basic.ibc
rm phase.ibc
rm preliminaries.ibc
rm serverupdates.ibc
rm skill_dsl.ibc
rm step_game.ibc
rm step_game_helpers.ibc
rm transform_game.ibc
rm transform_game_helpers.ibc

rm clean.sh~
rm build.sh~
rm clientupdates.idr~
rm elementalmagicks.ipkg~
rm main.idr~
rm objects_advanced.idr~
rm objects_basic.idr~
rm phase.idr~
rm preliminaries.idr~
rm serverupdates.idr~
rm skill_dsl.idr~
rm step_game.idr~
rm step_game_helpers.idr~
rm transform_game.idr~
rm transform_game_helpers.idr~
